/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppCanvas: typeof import('./src/components/appCanvas.vue')['default']
    AppContent: typeof import('./src/components/appContent.vue')['default']
    AppHeader: typeof import('./src/components/appHeader.vue')['default']
    AppLeft: typeof import('./src/components/appLeft.vue')['default']
    AppRight: typeof import('./src/components/appRight.vue')['default']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Logo: typeof import('./src/components/logo.vue')['default']
    NavBar: typeof import('./src/components/navBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserOperator: typeof import('./src/components/userOperator.vue')['default']
  }
}
